version: 2
jobs:
  build:
    working_directory: ~/fec-starter
    docker:
      - image: circleci/node: 10
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}

      - run:
          name: install-npm-fect
          command: npm install

      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: tests
          command: npm test
